environment:

  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

build: off

install:
  - "python setup.py install"

test_script:
  - "%PYTHON%\\python.exe test\\test_unit.py"
  - "%PYTHON%\\python.exe test\\test_fuzz.py"
