language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - python setup.py install

# command to run tests
script:
- "./test/test_unit.py"
- "./test/test_fuzz.py"

# blacklist
#branches:
#  except:
#    - experimental

# whitelist
branches:
  only:
    - master
